# Generated by Django 2.1.10 on 2020-03-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authTest', '0002_auto_20200303_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
