# Generated by Django 2.1.10 on 2020-03-04 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authTest', '0004_app_is_superuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='app',
            managers=[
            ],
        ),
    ]
